#dbHost: "localhost"
#dbPort: 3306
#dbDatabase: "fwechelon"
#dbUsername: "fweUser"
#dbPassword: "forgottenworld"

discourseUrl: "https://forum.forgottenworld.it"
discourseApiKey: :^)

tosUrl: "https://wikinew.forgottenworld.it/main/Termini"

forumActivationTimeout: 600