name: FWEchelon
version: 0.1.0
api-version: "1.16"
description: The ForgottenWorld bureaucracy plugin
author: Shivs (OhMeMuffin)
depend:
  - FWKotlinDeps
main: it.forgottenworld.echelon.FWEchelonPlugin
commands:
  fwechelon:
    description: Access FWEchelon functions.
    usage: /fwechelon
    aliases: [ fwechelon,ech ]
  minigame:
    description: Access minigame services.
    usage: /minigame
    aliases: [ join,leave ]
permissions:
  fwechelon:
    description: Allows the player to use /fwechelon
    default: op
  fwechelon.reload:
    description: Allows the player to use /fwechelon reload
    default: op
  minigame:
    description: Allows the player to use /minigame
    default: true
  minigame.join:
    description: Allows the player to use /minigame join
    default: true
  minigame.leave:
    description: Allows the player to use /minigame leave
    default: true