name: FWEchelon
version: 0.0.1-SNAPSHOT
api-version: "1.16"
description: The ForgottenWorld bureaucracy plugin
author: Shivs (OhMeMuffin)
main: it.forgottenworld.echelon.FWEchelonPlugin
commands:
  fwechelon:
    description: Access FWEchelon functions.
    usage: /fwechelon
    aliases: [fwechelon,ech]
permissions:
  fwechelon:
    description: Allows the player to use /fwechelon
    default: op